import antfu from '@antfu/eslint-config'

export default antfu({
  typescript: true,
  ignores: [
    '**/dist/**',
    '**/.nuxt/**',
    '**/.output/**',
    '**/.turbo/**',
    '**/.data/**',
    '**/target/**',
    '**/*.md',
    '**/*.toml',
    '**/*.json',
  ],
  rules: {
    'node/prefer-global/process': 'off',
    'node/prefer-global/buffer': 'off',
    'no-new': 'off',
    'no-console': 'off',
    'no-alert': 'off',
    'dot-notation': 'off',
    'prefer-template': 'off',
    'style/brace-style': 'off',
    'style/max-statements-per-line': 'off',
    'style/no-multi-spaces': 'off',
    'style/quote-props': 'off',
    'style/operator-linebreak': 'off',
    'style/indent-binary-ops': 'off',
    'style/comma-dangle': 'off',
    'style/padded-blocks': 'off',
    'style/member-delimiter-style': 'off',
    'antfu/if-newline': 'off',
    'antfu/top-level-function': 'off',
    'antfu/consistent-list-newline': 'off',
    'ts/method-signature-style': 'off',
    'unused-imports/no-unused-imports': 'off',
    'regexp/no-super-linear-backtracking': 'off',
    'perfectionist/sort-imports': 'off',
    'perfectionist/sort-named-imports': 'off',
    'perfectionist/sort-named-exports': 'off',
    'perfectionist/sort-exports': 'off',
    'import/no-duplicates': 'off',
    'unicorn/prefer-number-properties': 'off',
    'jsonc/sort-keys': 'off',
    'markdown/fenced-code-language': 'off',
    'toml/array-bracket-spacing': 'off',
    'toml/array-element-newline': 'off',
  },
})
